### ISSUE TITLE
small installation guide for those on RN 0.42 that worked for me. [iOS]

### ISSUE THREAD

**Issue by grundmanise** [airbnb/react-native-maps#1116]
For anyone on RN 0.42.0. having weird issues and wondering on how to properly install:

My solution was:

`npm install react-native-maps@0.13.0 --save`
`react-native link react-native-maps`

then to enable `Google Maps` I followed https://gist.github.com/heron2014/e60fa003e9b117ce80d56bb1d5bfe9e0

This pod worked for me:

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target ‘ProjectName’ do
  # Fixes required for pod specs to work with rn 0.42
  react_native_path = "../node_modules/react-native"
  pod "Yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod "React", :path => react_native_path

  pod 'GoogleMaps'  # <~~ remove this line if you do not want to support GoogleMaps on iOS

end
```

also including `$(SRCROOT)/../node_modules/react-native-maps/ios/AirMaps` was unnecessary because `$(SRCROOT)/../node_modules/react-native-maps/ios` was already included by linking and it was set to recursive.

```
    "react": "15.4.2",
    "react-native": "0.42.0",
    "react-native-maps": "^0.13.0",
```

**Comment by jbfroment** [comment]
Forcing the 0.13 version solved a blank map problem I had switching from 0.41.2 to 0.42, along with some iOS compilation errors I had with 0.41.2.

Thanks for the post !

**Comment by lelandrichardson** [comment]
Closing this. but it would be great if you could make a PR to the docs if you have something for the installation process that you would like to add!
