### ISSUE TITLE
Memory Leak while using Navigator

### ISSUE THREAD

**Issue by DennisSnijder** [airbnb/react-native-maps#795]
i am using the map in a sub scene, once i unmount the component (componentWillUnmount is being called) the memory is not getting cleaned.

This will result into the app building up more and more memory which ends up in the app crashing.

**Comment by DennisSnijder** [comment]
Still no update on this?
Also on Android this causes the App to crash really quickly.

**Comment by DennisSnijder** [comment]
After some experimentation i found out the 'react-native-router-flux' affects the memory leak.
If u use this router it takes 80mb every time i open up a map, if i remove the router it only takes 8-10MB.

I still think this 8-10MB of memory not getting cleaned is an issue.

**Comment by gregberns** [comment]
@DennisSnijder I'm seeing the same issue, have you found a resolution to this issue?

I was wondering if there was a way to change the way the router loaded/unloaded the map component, but I haven't found anything.

The app crashes after 12 opens of a map on the Android phone I'm using.

**Comment by mmoravec** [comment]
@gregberns @DennisSnijder I'm seeing the same issue. My app continually gets laggier and laggier until it crashes. I'm using exponent's ex-navigation router and seeing the same thing.

**Comment by karpoff** [comment]
issue is present in 0.13.1 version
this is critical issue
memory is not freed after map unmounting

**Comment by lelandrichardson** [comment]
I believe this is fixed in #1130

**Comment by karpoff** [comment]
Hi @lelandrichardson, thanks for the update
I've checked latest react-native commit and I see that my react-native application shows error "Unknown plugin module-resolver". I believe it is caused by https://github.com/airbnb/react-native-maps/commit/6cd30add6b95ae69f0fbdc2a14adfbc394ed2a1e
Is it known issue? Or maybe there is some workaround for this?

**Comment by lelandrichardson** [comment]
@karpoff thanks for flagging this to me. I need to add `.babelrc` to the `.npmignore`!

**Comment by Exilz** [comment]
@lelandrichardson so that means we won't be able to use a specific commit from this repo in `package.json` without deleting `.babelrc` everytime then ?

**Comment by lelandrichardson** [comment]
@Exilz that's a reasonable use case that I hadn't considered, but this is really a problem with the packager and not with this library - as has been discussed countless times in the RN repo :/

The hack that we use at airbnb (and yes it is a hack) is to include this in our postinstall npm script:

```
"rm:babelrc": "(find node_modules -type f -name .babelrc | grep -v /react-native/ | xargs rm) || true",
```

This is a problem with so many libraries, but this fixes it well enough for us that i rarely think about it anymore... 

Of course you could also install the module resolver plugin as well if you'd like.

More discussion:

https://github.com/facebook/react-native/issues/10966
https://github.com/facebook/react-native/issues/4062
https://github.com/facebook/react-native/pull/6302

**Comment by privateOmega** [comment]
@lelandrichardson  Installing module-resolver plugin did not solve my problem as it displayed x.match is not a function. Also, how to include the above script in postinstall script?

**Comment by mbizplus** [comment]
same problem here 

> TransformError: /Users/macpro/Desktop/nasaapp/apps/nasaapp/node_modules/react-native-maps/index.js: ENOENT: no such file or directory, open '/Users/macpro/Desktop/nasaapp/apps/nasaapp/node_modules/react-native-maps/.babelrc'

**Comment by Sharnw** [comment]
Switched to react-native-maps v0.13.0, still getting the same error "x.match is not a function" :(

**Comment by sangagung** [comment]
@Sharnw how did you move to 0.13.0? I tried running `npm install react-native--maps@0.13.1` and I was presented with '404 error not in npm registry' messages

**Comment by Sharnw** [comment]
Try 'npm install react-native-maps@0.13.0', or add "react-native-maps": "0.13.0" to your package.json file then run 'npm update'.

**Comment by privateOmega** [comment]
@sangagung was that the same command you used? `npm install react-native**--**maps@0.13.1` too many `-`. `npm install react-native-maps@0.13.0` I hope this should help like @Sharnw pointed out.

**Comment by jeffmath** [comment]
The "x.match is not a function" issue occurred for me when I installed module-resolver instead of babel-plugin-module-resolver.  The latter is the dependency specified in the package.json file of react-native-maps.

**Comment by privateOmega** [comment]
@jeffmath  try switching to v0.13.0 of react-native-maps

**Comment by jeffmath** [comment]
@privateOmega, my message was intended to help those who are having the "x.match is not a function" issue.  Using babel-plugin-module-resolver works for me with v0.14.0.

**Comment by dominathan** [comment]
Correct as above

for react-native-maps v0.14.0, 
`cd ./node_modules/react-native-maps`
`npm install --save-dev babel-plugin-module-resolver`

open .babelrc and change module-resolver to babel-plugin-module-resolver

**Comment by Tavernari** [comment]
It's works! 👍 @dominathan

**Comment by frozenxis** [comment]
@dominathan , after i do that, i get 

> No such file or directory: '/Users/xis/Documents/ReactNativeProjects/FitExpress/node_modules/react-native-maps/lib/ios/AirMaps/RCTConvert+MapKit.m'

and 

> Native component for "AIRMap" does not exist


did you encounter this?

**Comment by dominathan** [comment]
@frozenxis See #1193
Open XCode then
> open AirMaps project inside Libraries folder
remove reference of RCTConvert+MapKit.h/m
add reference to RCTConvert+AirMap.h/m (from node_modules/react-native-maps/lib/ios/AirMaps)

Add reference by right clicking and select "Add Files to 'yourproject'"

**Comment by frozenxis** [comment]
@dominathan that fixed my problem, Thanks!
