### ISSUE TITLE
[iOS] Xcode won't build project after update from 0.16.0 to 0.16.1.

### ISSUE THREAD

**Issue by ivangrga** [airbnb/react-native-maps#1560]
### Error: "_OBJC_CLASS_$_GlobalVars", referenced from:
objc-class-ref in AIRGoogleMapMarker.o
ld: symbol(s) not found for architecture arm64

### Error: clang: error: linker command failed with exit code 1 (use -v to see invocation)

When I revert version to 0.16.0 Xcode is able to build project.

**Comment by christopherdro** [comment]
Hmm I am able to build the project. The issue stems from this commit b908c08ac2367652249918f4f5694eaf17a1eac2.

Does the Xcode build output give you any more information on what line the error is coming from?

**Comment by ivangrga** [comment]
No, this is only info i get, and when i downgrade back to 16.0.0 it builds.

**Comment by connected-space** [comment]
We've got the same problem.

![screen shot 2017-08-17 at 16 08 45](https://user-images.githubusercontent.com/28143488/29419202-6416c600-8366-11e7-886c-adcb89a1a75e.png)

**Comment by christopherdro** [comment]
I've reverted this commit and release a new version until we can figure out why some people are running into build issues.

https://github.com/airbnb/react-native-maps/releases/tag/v0.16.2

**Comment by kesha-antonov** [comment]
+1

**Comment by connected-space** [comment]
@christopherdro 

Can confirm that v0.16.2 builds successfully.

Thanks

**Comment by christopherdro** [comment]
Sweet!

**Comment by christopherdro** [comment]
Sweet!
